<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AccountController;
use App\Http\Controllers\Api\AccountDeleteController;
use App\Http\Controllers\Api\AccountUpdateController;
use App\Http\Controllers\Api\AuditLogController;
use App\Http\Controllers\Api\BackupController;
use App\Http\Controllers\Api\BudgetController;
use App\Http\Controllers\Api\DebtController;
use App\Http\Controllers\Api\HouseholdMemberController;
use App\Http\Controllers\Api\HouseholdController;
use App\Http\Controllers\Api\HouseholdDashboardController;
use App\Http\Controllers\Api\HouseholdReportController;
use App\Http\Controllers\Api\ReceiptController;
use App\Http\Controllers\Api\ReceiptAttachmentController;
use App\Http\Controllers\Api\ReceiptCompleteController;
use App\Http\Controllers\Api\ReceiptUpdateController;
use App\Http\Controllers\Api\RecurringRuleController;
use App\Http\Controllers\Api\SavingsGoalController;
use App\Http\Controllers\Api\SyncController;
use App\Http\Controllers\Api\TransferController;
use App\Http\Controllers\Api\TransactionController;
use App\Http\Controllers\Api\TransactionIndexController;
use App\Http\Controllers\Api\TransactionDeleteController;
use App\Http\Controllers\Api\TransactionUpdateController;
use App\Http\Controllers\Api\UpcomingBillController;
use App\Http\Middleware\EnsureHouseholdMembership;
use Illuminate\Support\Facades\Route;

Route::post('auth/register', [AuthController::class, 'register']);
Route::post('auth/login', [AuthController::class, 'login']);

Route::middleware(['auth:sanctum'])->group(function () {
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::get('auth/me', [AuthController::class, 'me']);
    Route::get('auth/sessions', [AuthController::class, 'sessions']);
    Route::get('auth/tokens', [AuthController::class, 'tokens']);
    Route::post('auth/tokens/rotate', [AuthController::class, 'rotate']);
    Route::delete('auth/tokens/current', [AuthController::class, 'revokeCurrentDevice']);
    Route::delete('auth/tokens', [AuthController::class, 'revokeAllTokens']);
    Route::delete('auth/tokens/{tokenId}', [AuthController::class, 'revokeToken']);
    Route::get('households', [HouseholdController::class, 'index']);
    Route::post('households', [HouseholdController::class, 'store']);
    Route::prefix('households/{household}')->middleware(EnsureHouseholdMembership::class)->group(function () {
        Route::get('dashboard', [HouseholdDashboardController::class, 'show']);
        Route::get('reports', [HouseholdReportController::class, 'show']);
        Route::get('audit-logs', AuditLogController::class);
        Route::get('backups', [BackupController::class, 'index']);
        Route::post('backups', [BackupController::class, 'store']);
        Route::get('budgets', [BudgetController::class, 'show']);
        Route::post('budgets', [BudgetController::class, 'store']);
        Route::get('recurring-rules', [RecurringRuleController::class, 'index']);
        Route::post('recurring-rules', [RecurringRuleController::class, 'store']);
        Route::get('upcoming-bills', [UpcomingBillController::class, 'index']);
        Route::post('upcoming-bills', [UpcomingBillController::class, 'store']);
        Route::get('savings-goals', [SavingsGoalController::class, 'index']);
        Route::post('savings-goals', [SavingsGoalController::class, 'store']);
        Route::post('savings-goals/{goal}/contributions', [SavingsGoalController::class, 'contribute']);
        Route::get('debts', [DebtController::class, 'index']);
        Route::post('debts', [DebtController::class, 'store']);
        Route::post('debts/{debt}/installments', [DebtController::class, 'installment']);
        Route::get('members', [HouseholdMemberController::class, 'index']);
        Route::post('members/invitations', [HouseholdMemberController::class, 'invite']);
        Route::post('accounts', [AccountController::class, 'store']);
        Route::put('accounts/{account}', AccountUpdateController::class);
        Route::delete('accounts/{account}', AccountDeleteController::class);
        Route::post('transactions', [TransactionController::class, 'store']);
        Route::get('transactions', TransactionIndexController::class);
        Route::get('transactions/export', [TransactionIndexController::class, 'export']);
        Route::post('transfers', [TransferController::class, 'store']);
        Route::put('transactions/{transaction}', TransactionUpdateController::class);
        Route::delete('transactions/{transaction}', TransactionDeleteController::class);
        Route::post('receipts', [ReceiptController::class, 'store']);
        Route::post('receipts/{receipt}/attachments', [ReceiptAttachmentController::class, 'store']);
        Route::put('receipts/{receipt}', ReceiptUpdateController::class);
        Route::post('receipts/{receipt}/complete', ReceiptCompleteController::class);
        Route::post('sync', [SyncController::class, 'store']);
    });
    Route::post('invitations/{token}/accept', [HouseholdMemberController::class, 'accept']);
});
